global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'paws360-auth'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'paws360-data'
    static_configs:
      - targets: ['data-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'paws360-analytics'
    static_configs:
      - targets: ['analytics-service:8083']
    metrics_path: '/actuator/prometheus'