---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paws360
  namespace: paws360
  labels:
    app: paws360

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paws360-role
  namespace: paws360
  labels:
    app: paws360
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paws360-rolebinding
  namespace: paws360
  labels:
    app: paws360
subjects:
- kind: ServiceAccount
  name: paws360
  namespace: paws360
roleRef:
  kind: Role
  name: paws360-role
  apiGroup: rbac.authorization.k8s.io
